In [1]:
import numpy as np
import pandas as pd
import joblib

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [2]:
df = load_iris(as_frame=True).frame

In [3]:
y = df.pop('target')
x = df.copy()

y = y.to_numpy()
x = x.to_numpy()

In [4]:
#dict.keys(load_iris())
#dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
targetnames = load_iris().target_names

In [5]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)

In [6]:
pipeline = Pipeline([
    ('model', 'passthrough')
])

param_grid = [
    {
        'model' : [SVC(probability=True)],
        'model__C': [0.1, 1, 10],
        'model__kernel' : ['linear', 'rbf']
    },
    {
        'model' : [RandomForestClassifier()],
        'model__n_estimators' : [50, 100],
        'model__max_depth': [None, 5, 10]
    }
]

grid = GridSearchCV(pipeline, param_grid, cv=5, n_jobs=1, scoring="accuracy")
grid.fit(xtrain, ytrain)
grid.best_params_

{'model': SVC(probability=True), 'model__C': 1, 'model__kernel': 'linear'}

In [7]:
best_model = grid.best_estimator_

ypred = best_model.predict(xtest)

In [8]:
print("classification report: \n", classification_report(ytest, ypred))
print("confusion matrix: \n", confusion_matrix(ytest, ypred))

classification report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

confusion matrix: 
 [[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]


In [9]:
joblib.dump(best_model, "svc_model.pkl")
print("\n model saved as svc_model.pkl")


 model saved as svc_model.pkl
